# Generated by Django 4.2 on 2026-02-15 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('main', models.TextField()),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='notice_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Protocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('頭部', '頭部'), ('頸部', '頸部'), ('胸部', '胸部'), ('腹部', '腹部'), ('下肢', '下肢'), ('上肢', '上肢'), ('特殊', '特殊')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('protocol_img', models.ImageField(blank=True, null=True, upload_to='protocol_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Protocols',
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesease', models.CharField(max_length=255, unique=True)),
                ('diesease_text', models.TextField()),
                ('keyword', models.CharField(blank=True, max_length=500)),
                ('protocol', models.CharField(blank=True, max_length=255)),
                ('protocol_text', models.TextField(blank=True)),
                ('processing', models.CharField(blank=True, max_length=255)),
                ('processing_text', models.TextField(blank=True)),
                ('contrast', models.CharField(blank=True, max_length=255)),
                ('contrast_text', models.TextField(blank=True)),
                ('diesease_img', models.ImageField(blank=True, null=True, upload_to='sick_images/')),
                ('protocol_img', models.ImageField(blank=True, null=True, upload_to='protocol_images/')),
                ('processing_img', models.ImageField(blank=True, null=True, upload_to='processing_images/')),
                ('contrast_img', models.ImageField(blank=True, null=True, upload_to='contrast_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Sicks',
                'ordering': ['diesease'],
            },
        ),
    ]
