# Generated by Django 4.2 on 2026-02-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_type', models.CharField(choices=[('export', 'バックアップ実行'), ('import', 'バックアップ復元')], default='export', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('success', '成功'), ('failed', '失敗')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Backup Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
