# Generated by Django 4.2 on 2026-02-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_app', '0002_backuphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocol',
            name='contrast_detail',
            field=models.TextField(blank=True, null=True, verbose_name='造影詳細'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='processing_detail',
            field=models.TextField(blank=True, null=True, verbose_name='画像処理詳細'),
        ),
        migrations.AddField(
            model_name='protocol',
            name='protocol_detail',
            field=models.TextField(blank=True, null=True, verbose_name='撮影詳細'),
        ),
        migrations.AlterField(
            model_name='protocol',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='概要'),
        ),
    ]
