# Generated by Django 4.2 on 2026-03-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ct_app', '0003_protocol_contrast_detail_protocol_processing_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='post_img10',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img2',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img3',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img4',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img5',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img6',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img7',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img8',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
        migrations.AddField(
            model_name='form',
            name='post_img9',
            field=models.ImageField(blank=True, null=True, upload_to='notice_images/'),
        ),
    ]
