# Generated by Django 4.2 on 2026-03-31 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_app', '0004_form_post_img10_form_post_img2_form_post_img3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='post_img',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img10',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img2',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img3',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img4',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img5',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img6',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img7',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img8',
        ),
        migrations.RemoveField(
            model_name='form',
            name='post_img9',
        ),
        migrations.CreateModel(
            name='NoticeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='notice_images/')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ct_app.form')),
            ],
        ),
    ]
