# Generated by Django 4.2 on 2026-04-01 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_app', '0005_remove_form_post_img_remove_form_post_img10_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SickImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sick_images/')),
                ('category', models.CharField(choices=[('disease', '疾患情報'), ('protocol', '撮影プロトコル'), ('contrast', '造影プロトコル'), ('processing', '画像処理')], max_length=20)),
                ('sick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ct_app.sick')),
            ],
        ),
        migrations.CreateModel(
            name='ProtocolImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='protocol_images/')),
                ('protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ct_app.protocol')),
            ],
        ),
    ]
