# Generated by Django 5.1.3 on 2026-04-01 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ct_app", "0006_sickimage_protocolimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="post_img",
            field=models.ImageField(blank=True, null=True, upload_to="post_images/"),
        ),
    ]
