# Generated by Django 4.2 on 2026-05-31 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ct_app', '0008_nightshift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nightshift',
            name='image',
        ),
        migrations.CreateModel(
            name='NightShiftImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='nightshift_images/')),
                ('nightshift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ct_app.nightshift')),
            ],
        ),
    ]
