# Generated by Django 4.2 on 2026-09-06 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily_assignment', '0021_comment_template_default_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentarea',
            name='overlap_assignment_mode',
            field=models.CharField(choices=[('never', '不可'), ('shortage', '人員不足時のみ可'), ('always', '常に可')], default='never', help_text='欠員再配置で、ほかの配置と同時間帯に兼任させてよいかを指定します。時間連動ルールの兼任はこの設定とは別に許可されます。', max_length=20, verbose_name='重複配置'),
        ),
    ]
